Add OTLPMetricPipeline builder methods for delta and lowmemory
open-telemetry/opentelemetry-rust pull request #1057
Opened 2023-05-09 06:28 UTC by cijothomas

## Changes

Add new builder methods to help build OTLP Metrics Pipeline with desired Temporality. This PR specifically adds
builders to support the "Delta" and "LowMemory" temporality preference from the spec:
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/otlp.md#additional-configuration

Note that the env variable support for the same (OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE), is *not* part of this PR, and will be offered as a separate PR.

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

2023-05-25 16:59 UTC, lzchen commented on opentelemetry-otlp/CHANGELOG.md
> +  Metric pipeline
Nit: Add PR #

2023-05-25 17:01 UTC, lzchen commented on opentelemetry-otlp/src/metric.rs
> +impl DeltaTemporalitySelector {
We have the same thing defined in [benches](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/benches/metric.rs#L73) currently. Is it worthwhile to consolidate this into a common place?

2023-05-31 05:02 UTC, hdost reviewed
Aside from the linting issues idea makes sense. Although I concur with @lzchen that maybe the selectors should be somewhere common, SDK perhaps. This would allow others to use them as well.

2023-05-31 05:03 UTC, hdost commented on opentelemetry-otlp/src/metric.rs
> +struct DeltaTemporalitySelector {
This seems like it deserves to be a `trait`.

2023-05-31 05:05 UTC, hdost commented on opentelemetry-otlp/src/metric.rs
> +    pub(crate) _private: (),
What's the benefit of this?

2023-06-01 19:24 UTC, jtescher approved these changes
I think this is basically good to merge, only a couple nits remaining.

2023-06-01 19:24 UTC, jtescher commented on opentelemetry-otlp/src/metric.rs
> +    fn new() -> Self {
nit: as the lint is pointing out, are you intending this to be `pub`? or should this be removed as it's not used.

2023-10-26 20:35 UTC, hdost requested changes
Need to rebase and fix lints.

2024-03-13 01:39 UTC, cijothomas commented
Closing as #1568 covered this.

2024-03-13 01:39 UTC, closed without merging