Remove span_builder from Tracer
open-telemetry/opentelemetry-rust pull request #1361
Opened 2023-11-09 19:41 UTC by cijothomas

## Changes

Removed `span_builder` from `Tracer`. The returned `SpanBuilder` was anyway not connected to the `Tracer`, so users still had to provide a `Tracer` to the `start` method! Removed the method in favor of just using `SpanBuilder`'s associated method to get one!

I am thinking of this as a necessary cleanup of unnecessary public APIs. If there is a desire in the future to bring back this method, we can do so, but this time, it should be linked to Tracer automatically, so there won't be any need to pass it to the "start" !

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

2023-11-09 20:17 UTC, jtescher commented
Yeah the API here is a little unfortunate as rust doesn't have variadic params. The intention was to have a "simple" api via `tracer.span(...)` and a "full" api via `tracer.span_builder(...).build()` but it was always awkward as the builder needed a reference back to the tracer to actually create the span. Possibly worth considering if there are better solutions than the current builder approach?

2023-11-09 21:58 UTC, shaun-cox approved these changes

2023-11-12 15:39 UTC, hdost requested changes
I was say let's have a solution for this first since we should probably have a solution to having span builder. Ideally we could have the span builder maintain a reference to the Tracer? Not sure why we couldn't do that.

2023-11-14 02:10 UTC, jtescher commented
@hdost yeah giving the builder a lifteime and a reference should be fine

2024-04-30 19:23 UTC, cijothomas commented
Closing old, inactive PRs. 
This could be resurrected in the future.

2024-04-30 19:23 UTC, closed without merging