[opentelemetry-otlp] adds an example HTTP exporter backed by Hyper
open-telemetry/opentelemetry-rust pull request #1861
Opened 2024-06-04 07:59 UTC by markdingram

Resolves #1659

Given the Pending Hyper 1.0 upgrade seems to make sense for Hyper 0.2 Client support to be provided as an example. 

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

2024-06-04 16:22 UTC, cijothomas commented
From 6/4/ community call:
Please see if we can use the existing examples, and add feature flags to it to showcase diff. http clients, instead of maintaining full examples for each of them.

2024-06-10 17:01 UTC, cijothomas commented
> From 6/4/ community call: Please see if we can use the existing examples, and add feature flags to it to showcase diff. http clients, instead of maintaining full examples for each of them.

@markdingram Would you be willing to change this based on this recommendation? Thanks in advance!

2024-06-11 07:27 UTC, markdingram commented
> > From 6/4/ community call: Please see if we can use the existing examples, and add feature flags to it to showcase diff. http clients, instead of maintaining full examples for each of them.
> 
> @markdingram Would you be willing to change this based on this recommendation? Thanks in advance!

I had a go

2024-06-14 15:19 UTC, cijothomas commented on opentelemetry-otlp/CHANGELOG.md
> +- Adds `hyper` feature to the basic-otlp-http example showing how to export with a custom Hyper Client
dont need a changelog entry for this.

2024-06-19 02:31 UTC, cijothomas commented on opentelemetry-otlp/examples/basic-otlp-http/README.md
> +By default the app will use a `reqwest` client to send. A hyper 0.14 client can be used with the `hyper` feature enabled
```suggestion
By default the app will use a `reqwest` client to send. A hyper client can be used with the `hyper` feature enabled
```

2024-06-19 02:32 UTC, cijothomas approved these changes
Thanks!
Will wait for one more approval to merge. (My own experience with hyper is limited, so need an extra pair of eyes)

2024-06-19 21:44 UTC, lalitb commented on opentelemetry-otlp/examples/basic-otlp-http/src/hyper.rs
> +use async_trait::async_trait;
Do you think we can instead update the [HttpConfig ](https://github.com/open-telemetry/opentelemetry-rust/blob/e0fb7fe3b7ab343cdf2f702b04d04976dc5542ca/opentelemetry-otlp/src/exporter/http/mod.rs#L53) in opentelemetry-otlp with the hyper client, and so not have the special handling here

2024-06-20 18:41 UTC, lalitb requested changes
@markdingram please see if this makes sense - https://github.com/open-telemetry/opentelemetry-rust/pull/1861#discussion_r1646709516

2024-06-24 07:08 UTC, markdingram commented
> @markdingram please see if this makes sense - [#1861 (comment)](https://github.com/open-telemetry/opentelemetry-rust/pull/1861#discussion_r1646709516)

Anything done now will conflict with https://github.com/open-telemetry/opentelemetry-rust/pull/1674 - I will look again once the rate upgrades are through.

2024-07-01 22:42 UTC, lalitb commented
> > @markdingram please see if this makes sense - [#1861 (comment)](https://github.com/open-telemetry/opentelemetry-rust/pull/1861#discussion_r1646709516)
> 
> Anything done now will conflict with #1674 - I will look again once the crate upgrades are through.

should be good, assuming we will revisit this once #1674 is through.

2024-07-01 22:42 UTC, lalitb approved these changes

2024-07-01 22:44 UTC, merged