resources map to jaeger process tags
open-telemetry/opentelemetry-rust pull request #215
Opened 2020-09-08 07:19 UTC by danrusei

#205 
I hope my understanding about what is requested here is correct, otherwise I'll modify based on the feedback.

2020-09-09 00:17 UTC, TommyCpp requested changes
Good start, thanks! have some suggestions

2020-09-09 00:17 UTC, TommyCpp commented on opentelemetry-jaeger/src/lib.rs
> +                for span in batch.iter() {
Could just use the `batch.into_iter()` and switching the following two line like 
```rust
process_tags.extend(build_process_tags(&span));
jaeger_spans.push(span.into());
```

2020-09-09 00:17 UTC, TommyCpp commented on opentelemetry-jaeger/src/lib.rs
> +impl Into<jaeger::Span> for &Arc<trace::SpanData> {
Probably no need to change this if we could just use `batch.into_iter()` above.

2020-09-09 11:19 UTC, danrusei commented on opentelemetry-jaeger/src/lib.rs
> +                let mut jaeger_spans: Vec<jaeger::Span> = Vec::new();
Thank you, I'm updating the PR with the suggested changes. But do we know the capacity of the process_tags ?

2020-09-09 14:38 UTC, TommyCpp commented on opentelemetry-jaeger/src/lib.rs
> +                let mut jaeger_spans: Vec<jaeger::Span> = Vec::new();
Ha sorry I was looking at the wrong variable. We don't know the capacity of the process tags.

2020-09-14 02:23 UTC, TommyCpp approved these changes
Sorry for the late reply. LGTM. Thanks!

2020-09-14 20:17 UTC, jtescher commented on opentelemetry-jaeger/src/lib.rs
> +                    process_tags.extend(build_process_tags(&span));
Will this duplicate these tags for every span?

2020-09-17 00:31 UTC, jtescher commented
@danrusei generally looks good, just want to make sure this won't add duplicate process tags when exporting batches of spans

2020-09-17 12:46 UTC, danrusei commented
> @danrusei generally looks good, just want to make sure this won't add duplicate process tags when exporting batches of spans

thank you, would this work ?

    for tag in build_process_tags(&span) {
                        if !process_tags.contains(&tag) {
                            process_tags.push(tag)
                        }
                    }

2020-09-17 16:25 UTC, jtescher commented
@danrusei That should work but it may do a lot of work checking each time. The resource _should_ be the same for all spans, so you could do something like `for (idx, tag) in tags.enumerate() { if idx == 0 { add tags} ... }` to only add them the first time?

2020-09-18 23:41 UTC, jtescher commented
Looks good @danrusei, just have to rebase and make sure tests pass

2020-09-20 14:42 UTC, jtescher approved these changes
Looks good thanks @danrusei

2020-09-20 14:43 UTC, merged