feat(otlp): add openssl feature flags for grpcio
open-telemetry/opentelemetry-rust pull request #367
Opened 2020-11-21 18:56 UTC by lucacasonato

`grpcio` has an `openssl` and `openssl-vendored` feature to use `openssl` instead of `boringssl`. This PR exposes these features through an `openssl` and `openssl-vendored` feature﻿ in `opentelemetry-otlp`.

2020-11-21 19:48 UTC, jtescher requested changes
Looks good, can we add the feature flag docs to lib.rs as well for consistency?

2020-11-21 21:13 UTC, TommyCpp approved these changes

2020-11-21 23:15 UTC, jtescher commented
Looks like just a `cargo fmt` issue remaining

2020-11-22 18:27 UTC, jtescher approved these changes

2020-11-22 18:27 UTC, merged