Prepare for v0.13.0 release
open-telemetry/opentelemetry-rust pull request #470
Opened 2021-03-08 02:12 UTC by TommyCpp

- Prepare CHANGELOGs to include PRs from #433. 
- Fix docs that still use tracer provider guard.
- Update the protobuf generated file version.

2021-03-08 04:47 UTC, jtescher commented on opentelemetry-prometheus/CHANGELOG.md
> +- Update `prometheus` dependency to v0.11 #435
think this already happened in 0.5.0?

2021-03-08 04:48 UTC, jtescher commented on opentelemetry/CHANGELOG.md
> +- Changed the default branch to `main` #439
Not sure we need this in the changelog, probably more of a housecleaning PR

2021-03-08 04:48 UTC, jtescher requested changes
Thanks @TommyCpp, just a couple comments

2021-03-08 05:41 UTC, djc commented
I feel like it might be better to try and get #467 and #469 in before we release, since they seem meaningful improvements with relatively large API impact?

2021-03-17 23:54 UTC, TommyCpp commented on examples/external-otlp-tonic-tokio/Cargo.toml
> +opentelemetry-otlp = { path = "../../opentelemetry-otlp", features = ["tonic", "tls", "tls-roots", "async"] }
Need to remove the `async` feature once the #483 removed

2021-03-24 01:44 UTC, jtescher approved these changes
Looks good, thanks @TommyCpp

2021-03-24 02:14 UTC, merged