otlp: mention service.name in kitchen sink cfg doc - closes #475
open-telemetry/opentelemetry-rust pull request #476
Opened 2021-03-10 22:11 UTC by clux

adds a possibly slightly more useful key/value combination for docs.

it's probably a common thing to want to set, even if it's not a thing that otel cares about.

2021-03-11 00:24 UTC, TommyCpp approved these changes

2021-03-11 00:25 UTC, TommyCpp requested changes
May need to do the same change in README?

2021-03-11 10:37 UTC, clux commented
Done.

Btw would you accept PR for adding `OtlpPipelineBuilder::with_service_name` like in [opentelemetry-jaeger](https://docs.rs/opentelemetry-jaeger/0.11.0/opentelemetry_jaeger/struct.PipelineBuilder.html#method.with_service_name)?

2021-03-11 16:14 UTC, TommyCpp commented
> Btw would you accept PR for adding `OtlpPipelineBuilder::with_service_name` like in [opentelemetry-jaeger](https://docs.rs/opentelemetry-jaeger/0.11.0/opentelemetry_jaeger/struct.PipelineBuilder.html#method.with_service_name)?
> Might cater to the common use case a bit more ergonomically.

Hmm, I guess the problem here is OTLP still doesn't have the `service.name` concept, `with_service_name` would be confusing if users are using a backend that doesn't recognize the `service.name` resource. But maybe we should make a note in the doc to explain if the backend recognizes a Jaeger-style service name, we can set it via resource.

2021-03-11 16:14 UTC, TommyCpp approved these changes

2021-03-11 16:27 UTC, jtescher requested changes

2021-03-11 16:27 UTC, jtescher commented on opentelemetry-otlp/README.md
> +                 with_resource(Resource::new(vec![KeyValue::new("service.name", "example")])),
```suggestion
                 .with_resource(Resource::new(vec![KeyValue::new("service.name", "example")])),
```

2021-03-11 17:44 UTC, clux commented on opentelemetry-otlp/README.md
> +                 with_resource(Resource::new(vec![KeyValue::new("service.name", "example")])),
ah, whoops :|

2021-03-11 17:45 UTC, clux commented on opentelemetry-otlp/README.md
> +                 .with_resource(Resource::new(vec![KeyValue::new("service.name", "example")])),
# #
```suggestion
                .with_resource(Resource::new(vec![KeyValue::new("service.name", "example")])),
```

2021-03-12 01:10 UTC, jtescher approved these changes

2021-03-12 01:10 UTC, merged