Split out `opentelemetry-api` and `opentelemetry-sdk`
open-telemetry/opentelemetry-rust pull request #735
Opened 2022-02-14 03:08 UTC by jtescher

* Split out `opentelemetry` crate into api and sdk crates, and re-export to maintain existing compatibility.
* Move `util` module to sdk as it was internal and not documented publicly.
* Remove api doc tests for now that relied on the sdk.
* Switch default text map propagator to be a noop (allowed by the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.8.0/specification/context/api-propagators.md#global-propagators))
* Move `ExportError` and `InstrumentationLibrary` to API.
* Move `SamplingResult` and `SamplingDecision` to trace API.

Closes #721

2022-02-14 17:25 UTC, hdost approved these changes
Seems like it still got some here and there fixes but 👍🏼  very nice

2022-02-14 19:44 UTC, hdost requested changes

2022-02-14 19:44 UTC, hdost commented on opentelemetry-api/src/lib.rs
> +//! *Compiler support: [requires `rustc` 1.46+][msrv]*
```suggestion
//! *Compiler support: [requires `rustc` 1.46+][msrv]*
//! [Prometheus]: https://prometheus.io
//! [Jaeger]: https://www.jaegertracing.io
//! [msrv]: #supported-rust-versions
```

2022-02-14 19:44 UTC, hdost commented on opentelemetry-api/src/baggage.rs
>  //! ```
```suggestion
```

2022-02-15 16:03 UTC, TommyCpp reviewed
A few questions about where to put the items but overall looks good :+1: This is a good start and we can address those issues in follow-up PR as this is already a big PR.

2022-02-16 15:25 UTC, jtescher commented on opentelemetry-api/src/trace/mod.rs
> +    pub dropped_attributes_count: u32,
Yeah wanted to get minimal diff first, can do cleanup PRs subsequently

2022-02-16 16:20 UTC, TommyCpp approved these changes
LGTM. I think we can merge once the two issue of comments above resolved.

2022-02-17 18:10 UTC, merged