[dd-metrics-encode]
open-telemetry/opentelemetry-rust pull request #792
Opened 2022-05-11 01:10 UTC by rex-remind101

encode sampling priority into metrics object of data dog exported data. data dog uses this to sample.

solves https://github.com/open-telemetry/opentelemetry-rust/issues/791

2022-05-24 05:48 UTC, TommyCpp commented
Need to format the code

2022-05-31 02:24 UTC, TommyCpp commented on opentelemetry-datadog/src/exporter/model/v05.rs
> +            rmp::encode::write_f64(&mut encoded, if span.span_context.is_sampled() { 1.0 } else { 0.0 })?;
Could we define some constant at `model/mod.rs` and reuse them across v3 and v5 exporter?

2022-05-31 02:24 UTC, TommyCpp requested changes
Have one nit and need to format the code but otherwise LGTM. Thanks for the help!

2022-06-01 05:21 UTC, rex-remind101 commented
amended my commit with the suggestions. attempted to use the EasyCLA but I'm receiving the following The Individual CLA option is not enabled for this project. Please to your administrator to enable the Individual CLA option for this project. so i'm not sure how to move forward on this.

2022-06-02 03:19 UTC, TommyCpp commented
> The Individual CLA option is not enabled for this project. Please to your administrator to enable the Individual CLA option for this project

Could you take a screenshot? It should be something like 
![image](https://user-images.githubusercontent.com/12531298/171545998-eb4545d8-0341-44dd-9f90-30f10b50fdd0.png)

2022-06-02 19:32 UTC, rex-remind101 commented
it worked this time

2022-06-03 03:34 UTC, TommyCpp commented
@rex-remind101 I think we need to bump the msrv to 1.56 to resolve the CI issues. Could you make the change in https://github.com/open-telemetry/opentelemetry-rust/blob/main/.github/workflows/ci.yml#L71 ?

I don't have the write access to the branch.

2022-06-06 17:47 UTC, rex-remind101 commented
@TommyCpp ready!

2022-06-08 21:19 UTC, rex-remind101 commented
@TommyCpp looks like there is still an error actually, could you help provide direction?

2022-06-09 03:15 UTC, TommyCpp commented
> @TommyCpp looks like there is still an error actually, could you help provide direction?

I think the problem is still the MSRV. Let me experiment with some versions and see which one we need to use.

2022-06-10 23:11 UTC, TommyCpp approved these changes
Sorry for the delay. LGTM. Thanks!

2022-06-10 23:11 UTC, merged