Fix deriving endpoint URLs from OTEL_EXPORTER_OTLP_ENDPOINT
open-telemetry/opentelemetry-rust pull request #950
Opened 2023-01-18 14:44 UTC by hlinnaka

According to the spec, if OTEL_EXPORTER_OTLP_ENDPOINT env variable is set, the full URL to use for traces is formed by appending "/v1/traces" to OTEL_EXPORTER_OTLP_ENDPOINT. Similarly, the metrics URL is formed by appending "/v1/metrics". We were doing this correctly in the grpc-tonic exporter, in `SpanExporter::new_tonic`, but the corresponding `SpanExporter::new_grpcio` and `SpanExporter::new_http` functions didn't get the memo. As a result, if you used the HTTP protocol or the grpcio implementation, and set
OTEL_EXPORTER_OTLP_ENDPOINT=http://foobar:4318/, the traces would be incorrectly sent to "http://foobar:4318/", when the correct destination would be "http://foobar:4318/v1/traces"

The timeout settings had similar issues; the per-signal TIMEOUT env variable was not always taken into account.

To fix, move the logic for forming the full URLs into ExporterConfig, and use it in all the different implementations. Similarly for the timeouts.

Add a test case with the three examples given in the OpenTelemetry specification.

2023-02-01 11:38 UTC, hdost reviewed
Looks good 👍🏼  thank you for the contribution, but you might need to rebase 😓  and do a little test cleanup.

2023-03-16 07:13 UTC, hdost requested changes

2023-03-16 07:13 UTC, hdost commented on opentelemetry-otlp/src/span.rs
> +        let channel = endpoint.timeout(traces.timeout()).connect_lazy();
I'm assuming this should be `config.traces_timeout()`

2023-03-16 07:13 UTC, hdost commented on opentelemetry-otlp/src/exporter/mod.rs
> +    pub(crate) fn metrics_endpoint(&self) -> String {
Since it's only used inside the crate: `#[cfg(feature = "metrics")]`

2023-03-16 07:13 UTC, hdost commented on opentelemetry-otlp/src/exporter/mod.rs
> +    pub(crate) fn metrics_timeout(&self) -> Duration {
Since it's only used inside the crate: `#[cfg(feature = "metrics")]`

2023-08-15 22:08 UTC, hlinnaka commented
> @hlinnaka There's been quite a few changes recently. If you feel comfortable you could rebase, or if you don't mind one of the maintainers can take a look at it.

Rebased. The underlying code had indeed changed quite a lot, so this looks a little different now. I don't think I'm going to spend any more time in the near future, so if you can take it from here, I would appreciate it!

This fixes the immediate issue, and I think this is a step in the right direction, but I'm still not 100% satisfied with the result:

- GrpcioExporterBuilder should use resolve_endpoint(), resolve_timeout(), resolve_compression() too. It does not currently use the env variables at all.

- What is the point of `with_env`? The env variables are used even if you don't call it. Well, except in grpcio.

- If you set a value explicitly by calling `WithExportConfig::with_endpoint()`, and the OTEL_EXPORTER_OTLP_ENDPOINT env variable is also set, the env variable is used. That seems wrong, surely the value given programmatically should take precedence.

2024-04-30 19:20 UTC, cijothomas commented
Closing old, inactive PRs. It'd be great if someone can take this over.

2024-04-30 19:20 UTC, closed without merging